services:
  postgres:
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=spring_modulith'
      - 'POSTGRES_PASSWORD=modulitha'
      - 'POSTGRES_USER=modulitha'
    ports:
      - '5432:5432'

    volumes:
      - /c/tmp/postgres_modulith:/var/lib/postgresql/data
volumes:
  postgres: